server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    url: jdbc:mysql://localhost:3306/mydatabase
    password: password
  application:
    name: history-migration
  cache:
    type: simple
